
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;

/**
 *
 * @author Eden
 * creates Settings form that allows the user to change
 * the broadcast name and file download location
 * and writes these to wifilesettings.properties
 * when done is pressed
 */
public class Settings extends javax.swing.JFrame {

    String proplocal = "wifilesettings.properties";
    OutputStream fos = null;

    public Settings() {
        initComponents();
        NameTextField.setText(WiFile.mProperties.getProperty(WiFile.DEVICE_KEY, "DNS"));
        FileTextField.setText(WiFile.mProperties.getProperty(WiFile.FILE_KEY, ""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        FileLabel = new javax.swing.JLabel();
        FileButton = new javax.swing.JButton();
        DoneButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        FileTextField = new JTextField();
        GeneralLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        FileLabel.setText("File Download Location");

        FileButton.setText("Open File Browser");
        FileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileButtonActionPerformed(evt);
            }
        });

        DoneButton.setText("Done");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });

        NameLabel.setText("Device Name (for broadcasting)");

        NameTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                NameTextFieldPropertyChange(evt);
            }
        });

        GeneralLabel.setText("General");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(DoneButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(NameLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(GeneralLabel)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(FileLabel)
                                                                .addGap(61, 61, 61)
                                                                .addComponent(FileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(170, 170, 170)
                                                                .addComponent(FileButton)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GeneralLabel)
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NameLabel)
                                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FileLabel)
                                        .addComponent(FileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FileButton)
                                .addGap(8, 8, 8)
                                .addComponent(DoneButton))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    //when the user presses the button to change the folder
    private void FileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileButtonActionPerformed
        // TODO add your handling code here:
        //creates a new FileBrowser so user can select the folder to store their files in
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FileBrowser b = new FileBrowser();
                String s = b.getReturnPath();
                FileTextField.setText(s);
            }
        });

    }//GEN-LAST:event_FileButtonActionPerformed

    //when the user presses done
    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileButtonActionPerformed
        // TODO add your handling code here:

        //writes new values to properties file when done is pressed
        try{
            fos = new FileOutputStream(proplocal);
            WiFile.mProperties.setProperty(WiFile.DEVICE_KEY, NameTextField.getText());
            WiFile.mProperties.setProperty(WiFile.FILE_KEY, FileTextField.getText());
            WiFile.mProperties.store(fos, null);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (fos != null) {
                try {
                    fos.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        //then disposes of the window
        this.dispose();

    }//GEN-LAST:event_FileButtonActionPerformed

    private void NameTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_NameTextFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FileButton;
    private javax.swing.JButton DoneButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel GeneralLabel;
    private javax.swing.JLabel FileLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField FileTextField;
    // End of variables declaration//GEN-END:variables
}
